version: "3.7"
services:
  php:
    image: juanluisbaptiste/apache-php:dev
    networks:
      - backend
    volumes:
      - ./volumes/wordpress:/var/www/html/
    container_name: php
  php-fpm:
    image: juanluisbaptiste/php-fpm:dev
    networks:
      - backend
    volumes:
      - ./volumes/wordpress/:/var/www/html/
    container_name: php-fpm
  apache-php-fpm:
    image: juanluisbaptiste/apache-php-fpm:dev
    networks:
      - backend
    volumes:
      - ./volumes/wordpress/:/var/www/html/
    container_name: apache-php-fpm

  # apache:
  #   image: juanluisbaptiste/apache:dev
  #   depends_on:
  #     - php-fpm
  #   networks:
  #     - frontend
  #     - backend
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./volumes/wordpress/:/var/www/html/
  #   container_name: apache
networks:
  frontend:
  backend:
