version: "3.7"
services:
  # php:
  #   build:
  #     context: './php/'
  #     args:
  #      PHP_VERSION: 7.1
  #   container_name: php
  php-fpm:
    build:
      context: './php-fpm/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    container_name: php-fpm
