version: "3.7"
services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: 7.0
    container_name: php-apache
  php-fpm:
    build:
      context: './php-fpm/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    container_name: php-fpm
